### ISSUE TITLE
Output files

### ISSUE THREAD

**Issue by DavideBrex** [eblancoga/spikChIP#3]
Hi,
Thank you for this nice tool, I recently tested it on some Chip-RX data from my lab.
I would like to ask for your help about a couple of issues  I faced.

Among the output files,  I get the **1000_avg_normalized_sample** only for the SPIKCHIP method. I converted this file to bedGraph and then to bigwig. However, I would like to create a bigwig also for the other normalization methods in order to compare them. How could I achieve this?

Moreover, when  I open in igv the output bigwigs files, for two samples of the same histone modification I get a high signal in the background regions that is also constant. I am struggling to understand what is happening. 

See here:
![image](https://github.com/eblancoga/spikChIP/assets/48018596/aa971e8a-f3b6-4b2e-978f-d8ec97fd4e44)

Sample 1 and 3 are from the same histone modification (H3K27Me3), whereas 2 and 4 are from H2Ak119ub1

Hope you can help me out.
Thanks!
Best

Davide

**Comment by eblancoga** [comment]
Dear Davide,

Thanks for using our software and for your feedback!

Please, let me go question by question:

- In principle you should find the same files for the rest of normalization methods
(https://github.com/eblancoga/spikChIP#output-folders-and-files) to generate
your custom tracks. We do have an option (-c) to keep all intermediate files in
the output folder, but main resulting files should be preserved in all types of normalizations.

- About the resulting profiles, spikChIP local normalization produces a more compact
distibution of peaks and valleys (but still clearly distinguishable) as all the data is normalized
together. Are you visualizing a region containing peaks of Polycomb (i.e. HoxA complex)? If we
could see the rest of normalization output profiles perhaps we can realize better what is
happening in your samples.

I hope this can help!

Enrique


________________________________________
Dr. Enrique Blanco García (PhD)
https://sites.google.com/site/eblancog2014/
http://orcid.org/0000-0001-6261-7370

Epigenetic Events in Cancer (L. Di Croce's lab)
Gene Regulation, Stem Cells and Cancer
Centre for Genomic Regulation (CRG)
C/ Dr. Aiguader, 88
08003 Barcelona
Spain


________________________________
De: Davide Bressan ***@***.***>
Enviado: lunes, 23 de octubre de 2023 10:23
Para: eblancoga/spikChIP ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [eblancoga/spikChIP] Output files (Issue #3)


Hi,
Thank you for this nice tool, I recently tested it on some Chip-RX data from my lab.
I would like to ask for your help about a couple of issues I faced.

Among the output files, I get the 1000_avg_normalized_sample only for the SPIKCHIP method. I converted this file to bedGraph and then to bigwig. However, I would like to create a bigwig also for the other normalization methods in order to compare them. How could I achieve this?

Moreover, when I open in igv the output bigwigs files, for one sample i get a really high signal in the background regions that is also constant. I am struggling to understand what is happening.

See here:
[image]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/48018596/277273009-aa971e8a-f3b6-4b2e-978f-d8ec97fd4e44.png__;!!D9dNQwwGXtA!UxTwo1Cd9udW3qlQERq5xO3qNSAic7hy5PUeSDkQWkgrHYwvBig5PXFz3nZHQOrZA4dmYkURsfQLXIDR5UjkuhWC8VJl$>

Sample 1 and 3 are from the same histone modification (H3K27Me), whereas 2 and 4 are from H2Ak119ub1

Hope you can help me out.
Thanks!
Best

Davide

**Comment by DavideBrex** [comment]
Dear Enrique,
Thank you for your prompt reply and support.

The tool runs without errors on my data, and I get all the outputs, but I am double-checking this to ensure I am not missing something in the log.

Indeed, for the other normalization methods, I get the output files:
SampleID_CHIPRX_1000_sample_avg_bg.txt.gz
SampleID_CHIPRX_1000_sample_avg_peaks.txt.gz
etc. 

but not the 1000_avg_normalized_sample.txt.gz, that is only for the SPIKCHIP.
I check the script and If I understood correctly this is the right behaviour (see [this line](https://github.com/eblancoga/spikChIP/blob/fe8cb4194211cf4723641ea15498d313c735a503/spikChIP.pl#L1185C1-L1185C129) and [this one ](https://github.com/eblancoga/spikChIP/blob/fe8cb4194211cf4723641ea15498d313c735a503/spikChIP.pl#L1412))

If I am wrong and instead I should get the normalized_sample files also for the other normalization methods then probably there is an issue in the files generation somewhere. 

Thanks again. 
Best,
Davide

**Comment by eblancoga** [comment]
Ok, I'll run the full pipeline here with the data we provide to check everything is ok.

Enrique

________________________________________
Dr. Enrique Blanco García (PhD)
https://sites.google.com/site/eblancog2014/
http://orcid.org/0000-0001-6261-7370

Epigenetic Events in Cancer (L. Di Croce's lab)
Gene Regulation, Stem Cells and Cancer
Centre for Genomic Regulation (CRG)
C/ Dr. Aiguader, 88
08003 Barcelona
Spain


________________________________
De: Davide Bressan ***@***.***>
Enviado: lunes, 23 de octubre de 2023 11:40
Para: eblancoga/spikChIP ***@***.***>
Cc: Enrique Blanco Garcia ***@***.***>; Comment ***@***.***>
Asunto: Re: [eblancoga/spikChIP] Output files (Issue #3)


Dear Enrique,
Thank you for your prompt reply and support.

The tool runs without errors on my data, and I get all the outputs, but I am double-checking this to ensure I am not missing something in the log.

Indeed, for the other normalization methods, I get the output files:
SampleID_CHIPRX_1000_sample_avg_bg.txt.gz
SampleID_CHIPRX_1000_sample_avg_peaks.txt.gz

but not the 1000_avg_normalized_sample.txt.gz, that is only for the SPIKCHIP.
I check the script and If I understood correctly this is the right behaviour (see this line<https://urldefense.com/v3/__https://github.com/eblancoga/spikChIP/blob/fe8cb4194211cf4723641ea15498d313c735a503/spikChIP.pl*L1185C1-L1185C129__;Iw!!D9dNQwwGXtA!RJgoHlmda9l9vkBXYp0mNk4q7_zbEWYp2m0j7yVu4VOcLLy1pGIEM-_nf59YPm5ijsy-8gj-Uix62gKtOiJUXGJubvX3$>)

If I am wrong and instead I should get the normalized_sample files also for the other normalization methods then probably there is an issue in the files generation somewhere.

Thanks again.
Best,
Davide

**Comment by DavideBrex** [comment]
Hi Enrique,
Sorry to bother you again. Do you have any update on this?
 Thank you!
Davide

**Comment by eblancoga** [comment]
Hi Davide,

I 've been exploring more in detail your issue (finally, sorry!).
Actually, the files for the generation of the genome-wide profiles
for the other classes of normalization are indeed generated (using
the option -c you clean other intermediate files but those ones are
always generated).

For historical reasons, the filename format for spikChIP normalization results
and for the other normalizations is subtly different, as you noticed it. Thus, as
you pointed out to me, all of these files are presented under the same format
and you can apply the same gawk command from the README to generate BedGraph
files that can be after converted into BigWigs.

(for spikChIP normalization)
results/FINAL_H3K79me2_25-75-75-25_SPIKCHIP_1000_avg_normalized_sample.txt.gz
results/FINAL_H3K79me2_25-75-75-25_SPIKCHIP_1000_max_normalized_sample.txt.gz

(and the rest of normalizations)
results/FINAL_H3K79me2_25-75-75-25_CHIPRX_1000_sample_avg.txt.gz
results/FINAL_H3K79me2_25-75-75-25_CHIPRX_1000_sample_max.txt.gz
results/FINAL_H3K79me2_25-75-75-25_RAW_1000_sample_avg.txt.gz
results/FINAL_H3K79me2_25-75-75-25_RAW_1000_sample_max.txt.gz
results/FINAL_H3K79me2_25-75-75-25_TAGREMOVAL_1000_sample_avg.txt.gz
results/FINAL_H3K79me2_25-75-75-25_TAGREMOVAL_1000_sample_max.txt.gz
results/FINAL_H3K79me2_25-75-75-25_TRADITIONAL_1000_sample_avg.txt.gz
results/FINAL_H3K79me2_25-75-75-25_TRADITIONAL_1000_sample_max.txt.gz

I've updated this information in the README, together with minor modifications
I've introduced in the spikChIP.pl script to customize the "_FLY" inside the code
much better than hard-coded as before (new option -e).

I hope this can definitely be helpful for you and you can generate the custom
tracks easily for the rest of normalizations.

Merry christmas!

Enrique


________________________________________

Dr. Enrique Blanco García (PhD)

https://sites.google.com/site/eblancog2014/

http://orcid.org/0000-0001-6261-7370

Epigenetic Events in Cancer (L. Di Croce's lab)
Gene Regulation, Stem Cells and Cancer
Centre for Genomic Regulation (CRG)

C/ Dr. Aiguader, 88

08003 Barcelona

Spain


________________________________
De: Davide Bressan ***@***.***>
Enviado: jueves, 2 de noviembre de 2023 17:55
Para: eblancoga/spikChIP ***@***.***>
Cc: Enrique Blanco Garcia ***@***.***>; Comment ***@***.***>
Asunto: Re: [eblancoga/spikChIP] Output files (Issue #3)


Hi Enrique,
Sorry to bother you again. Do you have any updated on this?
Thank you!
Davide
