### ISSUE TITLE
Bin size

### ISSUE THREAD

**Issue by tellyalogicalguy** [eblancoga/spikChIP#4]
Hi,

First of all, thank you for making this software.

I would like to use a bin size of 20 bp (or 50bp), because I would like higher ChIP-seq signal resolution.
Qn 1: Would I lose reliability of normalisation if I use bin sizes this small?

You mention "selection of this [1000 bp] was based on finding a balance between ChIP-seq resolution, and the computational memory demand and running time required for a more compact bin segmentation".
Qn 2: Could I get an idea of how memory demand and run time scales for smaller bin sizes please?

Thank you,
PGS

**Comment by eblancoga** [comment]
Hi Ganesh,

Thanks for using spikChIP to normalize your experiments!
About the bin size, this is also related to the accuracy of the ChIP-seq
technique in general, which in principle identifies peaks of about 150-300 bp.
This means that even forcing any software to focus on sites of 50 bps
you will not gain in performance or accuracy in the normalization or
in any other part of your ChIP-seq pipeline.

In any case, about the memory requirements of spikChIP, the direct translation
of setting 50 bps or 1000 bps is the number of bins in which your genome (human,
mouse, ...) will be fragmented inside spikChIP. The higher the number of bins, the
higher the memory requirements and the size of the resulting files. In our experience,
by fragmenting any genome in bins of 1000 or 2000 bps is nearly optimal to capture
most ChIP-seq events (histone marks, TFs).

Best,

Enrique


________________________________________

Dr. Enrique Blanco García (PhD)

https://sites.google.com/site/eblancog2014/

http://orcid.org/0000-0001-6261-7370

Epigenetic Events in Cancer (L. Di Croce's lab)
Gene Regulation, Stem Cells and Cancer
Centre for Genomic Regulation (CRG)

C/ Dr. Aiguader, 88

08003 Barcelona

Spain


________________________________
De: Ganesh Subramani ***@***.***>
Enviado: martes, 5 de diciembre de 2023 0:01
Para: eblancoga/spikChIP ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [eblancoga/spikChIP] Bin size (Issue #4)


Hi,

First of all, thank you for making this software.

I would like to use a bin size of 20 bp (or 50bp), because I would like higher ChIP-seq signal resolution.
Qn 1: Would I lose reliability of normalisation if I use bin sizes this small?

You mention "selection of this [1000 bp] was based on finding a balance between ChIP-seq resolution, and the computational memory demand and running time required for a more compact bin segmentation".
Qn 2: Could I get an idea of how memory demand and run time scales for smaller bin sizes please?

Thank you,
PGS

**Comment by tellyalogicalguy** [comment]
Thanks for replying Enrique.

The reason I want to use smaller bin sizes is so that I can show UCSC snapshots of RNA Pol II ChIP-seq signals for a few genes, some of which are 5kb - 10kb long. I lose too much resolution if I use 1kb bins in these snapshots.
I understand there is no gain in accuracy in the normalisation. Would there be any reason for loss of accuracy because of the smaller bin sizes?

Thank you,
Ganesh

**Comment by eblancoga** [comment]
Hi,

No, the accuracy will be even a bit better, but you will pay a higher price in terms of memory and disk needs for the larger number of bins in the genome fragmentation. For your biological scenario you could try 500 bp too, which may seem a value of compromise between both alternatives.

Best,

Enrique

________________________________________

Dr. Enrique Blanco García (PhD)

https://sites.google.com/site/eblancog2014/

http://orcid.org/0000-0001-6261-7370

Epigenetic Events in Cancer (L. Di Croce's lab)
Gene Regulation, Stem Cells and Cancer
Centre for Genomic Regulation (CRG)

C/ Dr. Aiguader, 88

08003 Barcelona

Spain

________________________________
De: Ganesh Subramani ***@***.***>
Enviado: martes, diciembre 5, 2023 5:36:55 p. m.
Para: eblancoga/spikChIP ***@***.***>
CC: Enrique Blanco Garcia ***@***.***>; Comment ***@***.***>
Asunto: Re: [eblancoga/spikChIP] Bin size (Issue #4)


Thanks for replying Enrique.

The reason I want to use smaller bin sizes is so that I can show UCSC snapshots of RNA Pol II ChIP-seq signals for a few genes, some of which are 5kb - 10kb long. I lose too much resolution if I use 1kb bins in these snapshots.
I understand there is no gain in accuracy in the normalisation. Would there be any reason for loss of accuracy because of the smaller bin sizes?

Thank you,
Ganesh
